name: Release Gem

on:
  push:
    tags:
      - 'v*.*.*'        # e.g. v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: |
          VERSION=$(ruby -e "require './lib/dirfy/version'; puts Dirfy::VERSION")
          gem build dirfy.gemspec

      - name: Push to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          VERSION=$(ruby -e "require './lib/dirfy/version'; puts Dirfy::VERSION")
          gem push "dirfy-${VERSION}.gem"