name: Release Gem

on:
  push:
    tags:
      - 'v*.*.*'        # e.g. v1.2.3

permissions:
  contents: write  # Needed to create releases
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake

      - name: Build gem
        run: |
          VERSION=$(ruby -e "require './lib/dirfy/version'; puts Dirfy::VERSION")
          gem build dirfy.gemspec

      - name: Upload gem as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gem-package
          path: "*.gem"

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(ruby -e "require './lib/dirfy/version'; puts Dirfy::VERSION")
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes "## Release ${{ github.ref_name }}
            
            This is an automated release. The gem has been built and is available as an artifact.
            
            **To publish to RubyGems:**
            1. Download the gem from this release or build locally: \`rake build\`
            2. Run: \`gem push pkg/dirfy-${VERSION}.gem\`
            3. Complete 2FA authentication in your browser
            
            **Changes:** See commit history for details." \
            "dirfy-${VERSION}.gem"