name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2, 3.3]
        os: [ubuntu-latest]
        include:
          # Add macOS testing for latest Ruby version
          - ruby: 3.3
            os: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby (and pin Bundler for Ruby < 3.0)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.4.13 # Pin to bundler 2.4.13 works on 2.7
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: Run specs with coverage
        run: bundle exec rake spec
        env:
          COVERAGE: true

      - name: Upload coverage reports (Ubuntu Ruby 3.3 only)
        if: matrix.os == 'ubuntu-latest' && matrix.ruby == '3.3'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: Run bundle audit
        run: |
          bundle exec bundle-audit check --update
