name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby (and pin Bundler for Ruby < 3.0)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.4.13 # Pin to bundler 2.4.13 works on 2.7
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: Run specs
        run: bundle exec rake spec
